/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autofile;

import java.util.ArrayList;
import java.sql.*;
import javax.swing.JOptionPane;

public class mainwindow extends javax.swing.JFrame {
    private String loginTime;
    private ArrayList<String> loggedInStudentIds;
            
    public mainwindow(ArrayList<String> studentIds, String loginTime) {
        this.loginTime = loginTime;
        this.loggedInStudentIds = studentIds;
        initComponents();
        displayWelcomeNames(studentIds);
        jtxtLoggedTime.setText("Logged in at: " + loginTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtwelcome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtneditaccount = new javax.swing.JButton();
        jtxtLoggedTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtwelcome.setText("jLabel1");
        getContentPane().add(jtxtwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 379, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jbtneditaccount.setText("Edit Account");
        jbtneditaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditaccountActionPerformed(evt);
            }
        });
        getContentPane().add(jbtneditaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jtxtLoggedTime.setText("Logged in at: ");
        getContentPane().add(jtxtLoggedTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtneditaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditaccountActionPerformed
        this.dispose();
        edituser edituser = new edituser(loggedInStudentIds, loginTime);
        edituser.setVisible(true);
        edituser.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jbtneditaccountActionPerformed

    /**
     * @param args the command line arguments
     */
    private void displayWelcomeNames(ArrayList<String> studentIds){
        StringBuilder welcomeMsg = new StringBuilder("Welcome\n");
        ArrayList<String> lastNames = new ArrayList<>();
        try{
            Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/complab", "postgres", "postgres");
            String sql = "SELECT first_name, last_name FROM public.student WHERE student_id = ?";
            
            for (String id : studentIds){
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, id);
                ResultSet  rs = pst.executeQuery();
                
                if (rs.next()){
                    String firstName = rs.getString("first_name");
                    String lastName = rs.getString("last_name");
                    welcomeMsg.append(" ").append(firstName).append(" ").append(lastName).append("\n");
                    lastNames.add(lastName.toLowerCase());
                }
                rs.close();
                pst.close();
            }
            con.close();
            jtxtwelcome.setText(welcomeMsg.toString());
            createStudentFolder(lastNames);
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error loading names: " + e.getMessage());
        }
    }
    private void createStudentFolder(ArrayList<String> lastNames) {
        // Get the Desktop path dynamically
        String userDesktopPath = System.getProperty("user.home") + "/Desktop";  // This works for most systems

        // Concatenate last names with underscores
        String folderName = String.join("_", lastNames); // Example: "garcia_reyes"

        // Create a folder on the Desktop
        java.io.File folder = new java.io.File(userDesktopPath + "/" + folderName);

        // Check if the folder already exists, create it if not
        if (!folder.exists()) {
            boolean created = folder.mkdirs(); // Create the folder (and parent dirs if needed)
            if (created) {
                System.out.println("Created folder: " + folder.getAbsolutePath());
            } else {
                System.out.println("Failed to create folder: " + folderName);
            }
        } else {
            System.out.println("Folder already exists: " + folderName);
        }
    }
    public static void main(String args[]) {
        ArrayList<String> studentIds = new ArrayList<>();
        studentIds.add("studentId1");
        studentIds.add("studentId2");
        studentIds.add("studentId3");
        studentIds.add("studentId4");
        studentIds.add("studentId5");
        String loginTime = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("MMMM dd, yyyy - hh:mm a"));
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainwindow(studentIds, loginTime).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtneditaccount;
    private javax.swing.JLabel jtxtLoggedTime;
    private javax.swing.JLabel jtxtwelcome;
    // End of variables declaration//GEN-END:variables
}
